services:
  nginx:
    image: nginx:latest
    networks:
      - nfra-network
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 8086:8080
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M
networks:
  infra-network:
    external: true