services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 100M