services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    restart: on-failure
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 9080:9080
      - 50000:50000
volumes:
  jenkins_home: