services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    restart: on-failure
    networks:
      - shared-network
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 9080:9080
      - 50000:50000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
volumes:
  jenkins_home:
networks:
  infra-network:
    external: true